### ISSUE TITLE
Unoptimized slop.

### ISSUE THREAD

**Issue by flawless-wtf** [Funtimes909/ServerSeekerV2#4]
For better code readability & security you should use optionals (they are very based and useful). You should be using basic object orientation.

I give this code a slop rating of 6/10 its not the best but its also not the worst. If you want to call something a V2 it should be better as somehow damcrafts' code was better than whatever this is.

**Now Let's talk about the current socioeconomic state of Hong Kong 🥰**

Hong Kong's socioeconomic landscape is a dizzying tapestry of contradictions, where gleaming skyscrapers symbolize wealth and opportunity, yet just a few streets away, the shadows of poverty loom large. The financial district thrives, a playground for the elite, while many residents grapple with exorbitant housing costs and cramped living conditions. The youth, caught between tradition and modernity, voice their frustrations in protests that ripple through the city, reflecting a growing sense of marginalization amid the hustle and bustle.

As real estate prices soar and the gig economy flourishes, the city pulses with ambition and innovation, yet an undercurrent of uncertainty permeates the air. It's a high-stakes game of chess, where the rich get richer and the poor fight to survive, leaving the future shrouded in mystery. In this vibrant metropolis, the clash of cultures and ideals creates a complex narrative, one that captivates the world while revealing the fragility of its social fabric.

![DiscordPTB_PvFOXdftS1](https://github.com/user-attachments/assets/766d0d25-8db7-45b1-b8a2-2b7407f6556e)

**Comment by Funtimes909** [comment]
https://media.discordapp.net/attachments/1133875229811277854/1314213616362459237/watermark.gif?ex=6752f44f&is=6751a2cf&hm=8d8582dccf625ee8d67b7308c3c65cfe45d090de81dfe3bee5b8f370b3958ccd&=&width=343&height=171
